version : '3'
services:
    harvester:
        build:
            context: ./src
        environment:
            - LATEXML_ADDRESS=latexml_daemon
            - LATEXML_PORT=8080
        env_file:
            .env
        volumes:
            - harvests:/mws_nlab_harvester/harvests/
            - ./nlab-content-html:/mws_nlab_harvester/nlab-content-html/
            - ./logs:/mws_nlab_harvester/logs/
        depends_on:
            - latexml_daemon
        restart: always
    latexml_daemon:
        build:
            context: ../latexml-mws-docker
            args:
                - LATEXML_VERSION=https://github.com/brucemiller/LaTeXML.git
                - OTHER_PLUGINS=https://github.com/MathWebSearch/LaTeXML-plugin-iTeX2MML.git
        restart: always
volumes:
    harvests:
        external: true
